[build-system]
requires = ["setuptools>=43.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "navigate-micro"
description = "Open source, smart, light-sheet microscopy control software."
authors = [{name = "The Dean Lab, UT Southwestern Medical Center"}]
readme = "README.md"
license-files = ["LICENSE.md"]
dynamic = ["version"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

requires-python = ">=3.9.7"
dependencies = [
    'matplotlib-inline==0.1.3',
    'PyYAML>=6.0',
    'pyserial==3.5',
    'PIPython==2.6.0.1',
    'nidaqmx==0.5.7',
    'tifffile',
    'scipy',
    'pyusb==1.2.1',
    'pandas',
    'pandastable==0.12.2.post1',
    'opencv-python',
    'numpy',
    'scikit-image',
    'zarr',
    'fsspec',
    'h5py',
    'requests',
    'psutil==6.0.0',
    ]

[project.scripts]
navigate = "navigate.main:main"

[project.optional-dependencies]
photometrics = [
    "PyVCAM"
    ]

kinesis = [
    "pylablib"
    ]

dev = [
    "pytest",
    "pytest-xvfb",
    "pytest-cov",
    "pre-commit",
    "pytest-rerunfailures",
    "ipykernel",
    "jupyterlab",
    "pydantic-ome-ngff==0.5.3"
    ]

docs = [
    "numpydoc",
    "nbconvert",
    "sphinx<6.0.0",
    "sphinx_rtd_theme",
    "sphinx-copybutton",
    "sphinx-issues",
    "sphinx-design",
    "pyyaml",
    "pydata_sphinx_theme==0.10.0rc2",
    "sphinx-toolbox",
    "mss",
    "codespell"
]

robot = [
    "mecademicpy",
]

[project.urls]
Source = "https://github.com/TheDeanLab/navigate"

[tool.setuptools.dynamic]
version = {file = "src/navigate/VERSION"}

[tool.coverage.run]
relative_files = true
