[build-system]
requires = ["setuptools>=43.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "navigate"
description = "Open source, smart, light-sheet microscopy control software."
authors = [{name = "The Dean Lab, UT Southwestern Medical Center"}]
readme = "README.md"
license = {file = "LICENSE.md"}
version = "0.0.9"
dynamic = ["version"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

requires-python = ">3.11, <3.14"
dependencies = [
    'PyYAML',
    'pyserial',
    'PIPython',
    'nidaqmx',
    'tifffile',
    'scipy',
    'pandas',
    'pandastable',
    'opencv-python',
    'numpy',
    'scikit-image',
    'zarr',
    'h5py',
    'requests',
    'psutil'
    ]

[project.scripts]
navigate = "navigate.main:main"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xvfb",
    "pytest-cov",
    "pre-commit",
    "ipykernel",
    "jupyterlab",
    "pydantic-ome-ngff"
    ]

spurious = [
    'matplotlib-inline',
    'pyusb',
    'fsspec',
]

docs = [
    "numpydoc",
    "nbconvert",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinx-copybutton",
    "sphinx-issues",
    "sphinx-design",
    "pyyaml",
    "pydata_sphinx_theme",
    "sphinx-toolbox"
]

robot = [
    "mecademicpy",
]

[project.urls]
Source = "https://github.com/TheDeanLab/navigate"

#[tool.setuptools.dynamic]
#version = {file = "src/navigate/VERSION"}
