[build-system]
requires = ["setuptools>=43.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "navigate-micro"
description = "Open source, smart, light-sheet microscopy control software."
authors = [{name = "The Dean Lab, UT Southwestern Medical Center"}]
readme = "README.md"
license-files = ["LICENSE.md"]
dynamic = ["version"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

requires-python = ">=3.11"
dependencies = [
    'matplotlib-inline',
    "pyyaml>=6.0.2",
    'pyserial>=3.5',
    'PIPython>=2.6.0.1',
    'nidaqmx>=0.5.7',
    "tifffile>=2024.2",
    "scipy>=1.14",
    "pandas>=2.1",
    'pandastable>=0.12.2.post1',
    "opencv-python>=4.10",
    "numpy>=2.0",
    "scikit-image>=0.22",
    'zarr<3.0.1',
    "fsspec>=2024.3.1",
    "h5py>=3.11",
    "requests>=2.31",
    'psutil==6.0.0',
    ]

[project.scripts]
navigate = "navigate.main:main"

[dependency-groups]
dev = [
    "pytest",
    "pytest-xvfb",
    "pytest-cov",
    "pre-commit",
    "pytest-rerunfailures",
    "ipykernel",
    "jupyterlab",
    "pydantic-ome-ngff==0.5.3"
    ]

docs = [
    "numpydoc",
    "nbconvert",
    "sphinx<6.0.0",
    "sphinx_rtd_theme",
    "sphinx-copybutton",
    "sphinx-issues",
    "sphinx-design",
    "pydata_sphinx_theme==0.10.0rc2",
    "sphinx-toolbox",
]

robot = [
    "mecademicpy",
]

[project.urls]
Source = "https://github.com/TheDeanLab/navigate"

[tool.setuptools.dynamic]
version = {file = "src/navigate/VERSION"}
