[pytest]
addopts =
    --strict-markers
    -m "not hardware"
    --cov=src/navigate
    --cov-report=xml
filterwarnings =
    ignore:'parseString' deprecated - use 'parse_string':DeprecationWarning
    ignore:'resetCache' deprecated - use 'reset_cache':DeprecationWarning
    ignore:'enablePackrat' deprecated - use 'enable_packrat':DeprecationWarning
    ignore:Please use 'pipython\\.pidevice\\.gcserror' instead:DeprecationWarning
    ignore::DeprecationWarning:pipython.*
markers =
    hardware: mark tests as run on physical hardware
    integration: mark tests that rely on external integrations (network/pip)
log_cli = true
testpaths =
    test
