[pytest]
addopts =
    --strict-markers
    -m "not hardware"
    --cov=./
    --cov-report=xml
markers =
    hardware: mark tests as run on physical hardware
log_cli = true
filterwarnings =
    ignore:Please use 'pipython\\.pidevice\\.gcserror' instead:DeprecationWarning
    ignore::DeprecationWarning:pipython.*
testpaths =
    test
