from .daq.daq_synthetic import SyntheticDAQ
from .camera.camera_synthetic import SyntheticCamera
from .filter_wheel.filter_wheel_synthetic import SyntheticFilterWheel
from .galvo.galvo_synthetic import SyntheticGalvo
from .remote_focus.remote_focus_synthetic import SyntheticRemoteFocus
from .shutter.laser_shutter_synthetic import SyntheticShutter
from .stages.stage_synthetic import SyntheticStage
from .zoom.zoom_synthetic import SyntheticZoom
from .lasers.laser_synthetic import SyntheticLaser