%YAML 1.2
---
version: 1
formatters:
  base:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s: %(message)s'
filters:
  performance_specs:
    (): ext://navigate.log_files.filters.PerformanceFilter
  not_performance:
    (): ext://navigate.log_files.filters.NonPerfFilter
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: base
    stream: ext://sys.stdout
    filters: [not_performance]
  vc_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: base
    filename: view_controller_info.log
    filters: [not_performance]
    mode: a
  vc_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: base
    filename: view_controller_debug.log
    filters: [not_performance]
    mode: a
loggers:
  view:
    level: DEBUG
    handlers: [console, vc_info, vc_debug]
    propagate: no
  controller:
    level: DEBUG
    handlers: [console, vc_info, vc_debug]
    propagate: no
  config:
    level: DEBUG
    handlers: [console, vc_info, vc_debug]
    propagate: no


# https://docs.python.org/3/library/logging.html#logrecord-objects
