microscopes:
  virtual_microscope:
    camera:
      defect_correct_mode: 2.0
      delay: 5.0
      flip_x: False
      flip_y: False
      hardware:
        camera_connection: 1
        serial_number: 1
        type: Synthetic
      settle_down: 5.0
      supported_channel_count: 5
    daq:
      camera_trigger_out_line: virtual/2
      hardware:
        type: Synthetic
      laser_port_switcher: virtual/4
      laser_switch_state: False
      master_trigger_out_line: virtual/1
      sample_rate: 100000
      trigger_source: virtual/3
    filter_wheel:
      available_filters:
        Far-Red: 2
        Green: 0
        Red: 1
      filter_wheel_delay: 0.03
      hardware:
        baudrate: 9600
        name: FW1
        port: 1
        type: Synthetic
        wheel_number: 1
    galvo:
       -
        hardware:
          axis: A
          channel: virtual/ao0
          max: 0.0
          min: -10.0
          type: Synthetic
        phase: 0.0
        waveform: sine
    laser:
       -
        onoff:
          hardware:
            axis: NA
            channel: virutla/do1
            max: 5.0
            min: 0.0
            type: Synthetic
        power:
          hardware:
            axis: NA
            channel: virtual/ao1
            max: 5.0
            min: 0.0
            type: Synthetic
        wavelength: 488
    mirror:
      hardware:
        flat_path: D:\Path\to\wcs\file
        type: Synthetic
      n_modes: 32
    remote_focus:
      hardware:
        axis: NA
        baudrate: 9600
        channel: virtual/ao2
        max: 10.0
        min: -10.0
        port: COM1
        type: Synthetic
    shutter:
      hardware:
        axis: NA
        channel: virtual\d01
        max: 5.0
        min: 0.0
        port: COM2
        type: Synthetic
    stage:
      f_max: 10000.0
      f_min: -10000.0
      f_offset: 0.0
      flip_f: False
      flip_x: False
      flip_y: False
      flip_z: False
      hardware:
        -
          axes: [x, y, z, f, theta]
          axes_mapping: [X, M, Y, F, R]
          baudrate: 0
          controllername: 
          device_units_per_mm: 1000.25
          distance_threshold: 5.0
          feedback_alignment: [90, 90, 90, 90, 90]
          max: 4.6
          min: 0.0
          port: COM3
          refmode: 
          serial_number: 
          settle_duration_ms: 20.0
          stages: 
          timeout: 0.25
          type: Synthetic
          volts_per_micron: 0.1*x+0.05
      joystick_axes: [x, y, z, f, theta]
      theta_max: 360.0
      theta_min: 0.0
      theta_offset: 0.0
      x_max: 10000.0
      x_min: -10000.0
      x_offset: 0.0
      y_max: 10000.0
      y_min: -10000.0
      y_offset: 0.0
      z_max: 6000.0
      z_min: -10000.0
      z_offset: 0.0
    zoom:
      hardware:
        baudrate: 9600
        port: COM4
        servo_id: NA
        type: Synthetic
      pixel_size:
        1x: 6.5
      position:
        1x: 1.0
