microscopes:
  Mesoscale:
    daq:
      hardware:
        type: NI
      sample_rate: 100000
      master_trigger_out_line: Dev1/port0/line10
      camera_trigger_out_line: /Dev1/ctr0
      trigger_source: /Dev1/PFI3
      laser_port_switcher: Dev1/port0/line11
      laser_switch_state: False
    
    zoom:
      hardware:
        type: synthetic
        servo_id: 1
        port: None
        baudrate: 
      position:
        N/A: 0.0
      pixel_size:
        N/A: 2.125
    
    shutter:
      hardware:
        type: synthetic
        channel: Dev1/port0/line16
        min: 0.0
        max: 5.0

    camera:
      hardware:
        type: Photometrics
        serial_number: A17K631096
        camera_connection: pvcamPCIE_0
      speed_table_index: 0
      readout_port: 0
      gain: 1
      defect_correct_mode: 1.0
      delay: 1.0
      settle_down: 0.0
      flip_x: False
      flip_y: False
      supported_channel_count: 4
    
    remote_focus_device:
      hardware:
        type: NI
        channel: Dev1/ao2
        min: 0.0
        max: 10.0
        port: None
        baudrate: 0   
    
    galvo:
      -
        name: 0
        hardware:
          type: NI
          channel: Dev1/ao1
          min: -5.0
          max: 5.0
        waveform: sine
        phase: 1.57079
      - 
        name: 1
        hardware:
          type: NI
          channel: Dev1/ao0
          min: -5.0
          max: 5.0
        waveform: sawtooth
        phase: 0

    filter_wheel:
      hardware:
        type: NI
        wheel_number: 1
        port: None
        baudrate: 
        name: None
      filter_wheel_delay: 0.05
      available_filters:
        473nm: Dev1/port0/line3
        532nm: Dev1/port0/line2
        561nm: Dev1/port0/line1
        638nm: Dev1/port0/line0
    
    lasers:
      -
        wavelength: 473
        onoff:
          hardware:
            type: NI
            channel: Dev1/port0/line7
            min: 0.0
            max: 5.0
        power:
          hardware:
            type: synthetic
            channel: none/ao4
            min: 0.0
            max: 5.0
      -
        wavelength: 532
        onoff:
          hardware:
            type: NI
            channel: Dev1/port0/line6
            min: 0.0
            max: 5.0
        power:
          hardware:
            type: synthetic
            channel: none/ao3
            min: 0.0
            max: 5.0
      -
        wavelength: 561
        onoff:
          hardware:
            type: NI
            channel: Dev1/port0/line5
            min: 0.0
            max: 5.0
        power:
          hardware:
            type: synthetic
            channel: none/ao2
            min: 0.0
            max: 5.0
      -
        wavelength: 638
        onoff:
          hardware:
            type: NI
            channel: Dev1/port0/line4
            min: 0.0
            max: 5.0
        power:
          hardware:
            type: synthetic
            channel: none/ao1
            min: 0.0
            max: 5.0
    
    mirror:
      hardware:
        type: SyntheticMirror
        flat_path: 
      n_modes: 32
    
    stage:    
      hardware:
        -
          type: MS2000
          serial_number: 1906420147517051597
          port: /dev/ttyUSB0
          baudrate: 115200
          axes: [x, y, z] # Software
          axes_mapping: [X, Y, Z] 
          feedback_alignment: [90, 90, 90, 90]
          max_speed_perc: 0.5
          axes_accel: [70,70,150]
          axes_velocity: [0.5,0.5,0.5]
        -
          type: KINESIS
          serial_number: "/dev/ttyUSB1"
          axes: [f]
          axes_mapping: [1]
          steps_per_um: 2008.623
          axes_channels: autofocus
          start: 14800
          max: 25
          min: 0
        -
          type: synthetic
          serial_number: 123
          axes: ['theta']
          axes_mapping: ['xylophone']
          feedback_alignment: None
          device_units_per_mm: 
          volts_per_micron: None
          min: 
          max: 
          distance_threshold: 
          settle_duration_ms: 
          controllername: None
          stages: None
          refmode: None
          stagesport: None
          baudrate: 
          timeout: 
      joystick_axes: ['x', 'y', 'z']
      x_min: -100000.0
      x_max: 100000.0
      y_min: -100000.0
      y_max: 100000.0
      z_min: -100000.0
      y_max: 100000.0
      z_min: -100000.0
      z_max: 100000.0
      theta_min: 0.0
      theta_max: 360.0
      f_min: -100000.0
      f_max: 100000.0
      x_offset: 0.0
      y_offset: 0.0
      z_offset: 0.0
      theta_offset: 0.0
      f_offset: 0.0
      flip_x: False
      flip_y: False
      flip_z: False
      flip_f: True
    
    zoom:
      hardware:
        type: synthetic
        servo_id: 1
        port: None
        baudrate: 
      position:
        N/A: 0.0
      pixel_size:
        N/A: 2.12500

gui:
  channels:
    count: 4
